sudo: true
dist: trusty

install:
  - sudo apt-get --yes install snapd
  - sudo snap install hugo

script:
  - /snap/bin/hugo

# Deploy to GitHub pages
deploy:
  provider: pages   
  skip_cleanup: true  
  github_token: $GITHUB_TOKEN # Set GITHUB_TOKEN in travis-ci.org settings dashboard
  local_dir: public
  repo: marco-kretz/marco-kretz.github.io
  target_branch: master
  
  on:
    branch: master
